# Generated by Django 4.0.2 on 2022-02-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('url_product', models.TextField()),
                ('url_img_prevue', models.TextField()),
                ('url_imgs', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('os_phone', models.CharField(max_length=10)),
                ('diagonal', models.IntegerField()),
                ('display_type', models.CharField(max_length=10)),
                ('display_height', models.IntegerField()),
                ('display_width', models.IntegerField()),
                ('display_resol', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('camera_count', models.IntegerField()),
                ('processor', models.CharField(max_length=10)),
                ('battery', models.IntegerField()),
            ],
        ),
    ]
