# Generated by Django 4.0.2 on 2022-02-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='title',
        ),
    ]
