# Generated by Django 4.0.2 on 2022-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('url_product', models.TextField(verbose_name='URL продукта')),
                ('url_img_prevue', models.TextField(verbose_name='IMG')),
                ('url_imgs', models.TextField(verbose_name='IMGs')),
                ('brand', models.CharField(max_length=10, verbose_name='Бренд')),
                ('model', models.CharField(max_length=25, verbose_name='Модель')),
                ('os_phone', models.CharField(max_length=10, verbose_name='OS')),
                ('diagonal', models.FloatField(verbose_name='Диагональ экрана')),
                ('display_type', models.CharField(max_length=10, verbose_name='Тип дисплея')),
                ('display_height', models.IntegerField(verbose_name='Высота дисплея')),
                ('display_width', models.IntegerField(verbose_name='Ширина дисплея')),
                ('display_resol', models.CharField(max_length=10, verbose_name='Ширина и высота дисплея')),
                ('ram', models.IntegerField(verbose_name='Оперативная память')),
                ('rom', models.IntegerField(verbose_name='Объем внутренней памяти')),
                ('camera_count', models.IntegerField(verbose_name='Количество камер')),
                ('processor', models.CharField(max_length=30, verbose_name='Процессор')),
                ('battery', models.IntegerField(verbose_name='Объём батареи')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
                'ordering': ['data_update'],
            },
        ),
    ]
